### ISSUE TITLE
Error in loading NWP with assignment results

### ISSUE THREAD

**Issue by PeterKucirek** [TravelModellingGroup/TMGToolbox#13]
I get the following the following error importing an NWP with assignment results:

```
Traceback (most recent call last):
  File "C:\PyCharm Projects\TMGToolbox\TMGToolbox\src\input_output\import_network_package.py", line 214, in run
    self._execute()
  File "C:\PyCharm Projects\TMGToolbox\TMGToolbox\src\input_output\import_network_package.py", line 273, in _execute
    self._batchin_transit_results(scenario, temp_folder, zf)
  File "inro\director\logging\trail.py", line 272, in __trace
  File "C:\PyCharm Projects\TMGToolbox\TMGToolbox\src\input_output\import_network_package.py", line 408, in _batchin_transit_results
    zf.extract(aux_transit_filename,temp_folder)
  File "C:\Program Files\INRO\Emme\Emme 4\Emme-4.2.7\Python27\lib\zipfile.py", line 1036, in extract
    member = self.getinfo(member)
  File "C:\Program Files\INRO\Emme\Emme 4\Emme-4.2.7\Python27\lib\zipfile.py", line 933, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: 'There is no item named None in the archive'
```
It looks like the aux. transit volumes are not version sensitive: these NWPs were exported using an older version which didn't include this feature. So the code is trying to find `aux_transit_filename` which does not exist.

I will put in a conditional to only batchin aux transit results if `aux_transit_filename` is not None. The other option is to **only** load transit assignment results if both `voltr` and `volax` are present. The latter approach is 'more pure' but I think it's less like the user might expect the code to behave.

There will be a PR pending

**Comment by PeterKucirek** [comment]
Closed with PR #14
