### ISSUE TITLE
Transit lines copy error

### ISSUE THREAD

**Issue by malamillo** [TravelModellingGroup/TMGToolbox#66]
Hi all,

The following error was generated when running the Copy Transit Lines tool:

```
TRACEBACK:
Traceback (most recent call last):
  File "inro\director\tool\tool.py", line 127, in _run
  File "F:\GGHM v3\EMME_4442_directory\TMGToolbox-dev-1.8\TMGToolbox\src\network_editing\network_comparison\copy_transit_lines.py", line 368, in run
    self._Execute()
  File "F:\GGHM v3\EMME_4442_directory\TMGToolbox-dev-1.8\TMGToolbox\src\network_editing\network_comparison\copy_transit_lines.py", line 513, in _Execute
    geometryType= ShapefileWriter.SHP_LINE_TYPE) as writer:
AttributeError: class Shapely2ESRI has no attribute 'SHP_LINE_TYPE'
```

Do you know on what circumstances this is generated? Using the latest TMGToolbox-dev-1.8 on EMME 4.4.4.3.

Kind regards.

**Comment by lunaxi7** [comment]
Hi @malamillo, 

We noticed this issue and fixed it recently. Could you try to pull the latest commit ("Fix Copy Transit Line tool (#65)") and try the tool again?

Please let us know how it works.

Best regards,
Luna

**Comment by malamillo** [comment]
@lunaxi7, perfect! 
Thank you.

**Comment by lunaxi7** [comment]
This issue has been solved. Other questions will be communicated via emails or a new issue will be opened if needed.
